language: python

# Used travis-ci guide as base: https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci

# ==================
# ===== Linux ======
# ==================
dist: focal
python:
  - 2.7
  - 3.7
  - 3.9
  - 3.10

matrix:
  include:
    # ====================
    # ======= OSX ========
    # ====================
    - name: "Python 2.7.14 on macOS 10.13"
      os: osx
      osx_image: xcode9.3   # Python 2.7.14_2 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python --version
        # - pip install -U pip
        # - python -m pip install --upgrade pip
        - pip install pytest --user
        - pip install pytest-cov --user
        - pip install codecov --user
        - pip install flake8 --user
      install: pip install --user -r requirements.txt # install dependencies
      before_script:
        - python -m flake8 --exclude ./config,./github,./scripts,./tests --ignore=E501
      script: python -m pytest --cov=./ --cov-report=xml # run tests
      after_success: python -m codecov
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install pytest-cov
        - pip3 install codecov
        - pip3 install flake8
      script: python3 -m pytest --cov=./ --cov-report=xml # run tests
      after_success: python 3 -m codecov
    - name: "Python 3.? on macOS 11.3"
      os: osx
      osx_image: xcode12.5  # Python 3.? running on macOS 11.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install pytest-cov
        - pip3 install codecov
        - pip3 install flake8
      script: python3 -m pytest --cov=./ --cov-report=xml # run tests
      after_success: python 3 -m codecov
    # =========================
    #  ====== WINDOWS =========
    # =========================
    - name: "Python 2.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' errors Travis CI Windows
      before_install:
        - choco install python2
        - python --version
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
        - pip install pytest-cov
        - pip install codecov
        - pip install flake8
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install pytest-cov
        - pip3 install codecov
        - pip3 install flake8
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.9.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.9.0
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install pytest-cov
        - pip3 install codecov
        - pip3 install flake8
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
    - name: "Python 3.10.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.10.0
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install pytest-cov
        - pip3 install codecov
        - pip3 install flake8
      env: PATH=/c/Python310:/c/Python310/Scripts:$PATH

cache:
  - pip

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install flake8

install: python -m pip install -r requirements.txt # install dependencies

before_script:
  - flake8 --exclude ./config,./github,./scripts,./tests --ignore=E501

script: pytest --cov=./ --cov-report=xml # run tests

after_script:
  - python main.py
  - python main.py -h
  - python main.py does_not_exist.xml
  - python main.py config/simr.xml
  - python main.py tests/run_example.xml

after_success:
  - codecov # submit coverage
