language: python

python:
  - "2.7"
  - "3.8"

os:
  - linux
  - windows

cache:
  - pip

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - py.test

after_script:
  - python main.py
  - python main.py -h
  - python main.py does_not_exist.xml
  - python main.py config/simr.xml
  - python main.py tests/run_example.xml

after_success:
  - flake8 --ignore=E501
